name: theme_extensions_builder
description: >
  Code generator for Flutter's 3.0  ThemeExtension classes.
  theme_extensions_builder generator helps to minimize the required boilerplate code.

repository: https://github.com/pro100andrey/theme_extensions_builder
issue_tracker: https://github.com/pro100andrey/theme_extensions_builder/issues
homepage: https://github.com/pro100andrey/theme_extensions_builder
documentation: https://github.com/pro100andrey/theme_extensions_builder/blob/main/packages/theme_extensions_builder/README.md

version: 7.1.0

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

topics:
 - theme
 - extension
 - codegen

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  analyzer: ">=8.1.1 <10.0.0"
  build:  ">=3.0.0 <5.0.0"
  code_builder: ^4.11.1
  collection: ^1.19.1
  meta: ^1.16.0
  source_gen: ">=3.0.0 <5.0.0"
  theme_extensions_builder_annotation: ^7.1.0

dev_dependencies:
  build_test: "^3.5.5"
  path: ^1.9.1
  pro_lints: ^5.1.0
  source_gen_test: ^1.3.4
  test: ^1.29.0
  