name: theme_extensions_builder
description: > 
  Code generator for Flutter's 3.0  ThemeExtension classes. 
  theme_extensions_builder generator helps to minimize the required boilerplate code.

repository: https://github.com/pro100andrey/theme_extensions_builder
issue_tracker: https://github.com/pro100andrey/theme_extensions_builder/issues
homepage: https://github.com/pro100andrey/theme_extensions_builder
documentation: https://github.com/pro100andrey/theme_extensions_builder/blob/main/packages/theme_extensions_builder/README.md

version: 2.0.1+2

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  analyzer: ">=4.6.0 <6.0.0"
  build_config: ^1.1.1
  build: ^2.3.1
  meta: ^1.8.0
  theme_extensions_builder_annotation: ^2.0.0
  source_gen: ^1.2.6

dev_dependencies:
  flutter_lints: ^2.0.1
