name: example
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  theme_extensions_builder_annotation: ^7.0.0

dev_dependencies:
  build_runner: ^2.10.4
  pro_lints: ^5.0.0
  theme_extensions_builder: ^6.0.1

flutter:
  uses-material-design: true
