name: example
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  theme_extensions_builder_annotation: ^2.0.0

dev_dependencies:
  build_runner: ^2.3.3
  theme_extensions_builder: ^2.0.1+2
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
