name: Dart CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Install dependencies (annotation)
        working-directory: packages/theme_extensions_builder_annotation
        run: dart pub get

      - name: Run formatter check (annotation)
        working-directory: packages/theme_extensions_builder_annotation
        run: dart format --set-exit-if-changed .

      - name: Run tests (annotation)
        working-directory: packages/theme_extensions_builder_annotation
        run: dart test

      - name: Install dependencies (builder)
        working-directory: packages/theme_extensions_builder
        run: dart pub get

      - name: Run formatter check (builder)
        working-directory: packages/theme_extensions_builder
        run: dart format --set-exit-if-changed .

      - name: Run tests (builder)
        working-directory: packages/theme_extensions_builder
        run: dart test
